---
title: "About Me"
subtitle: "Learn a bit more about me"
---

## Who I am  
I am currently in my final year of DCU pursuing a degree in International Business with French, specialising in Data Analytics. I've always loved the idea of knowing different languages and living and studying in France aided this, expanded my worldview and deepened my appreciation for diverse cultures.  As well as this the ability to transform data and gain insights is what led to my choice of specialism. Although data analytics was not something I had a huge amount of experience studying in my pervious years, my love for continous learning helped me a lot. Now I can say that I have developed a strong foundation within data analytics! As someone who also loves anything art related, my creativity allows me to analyse things from different perspectives and beyond numbers data analytics allows me to connect logic with creativity. There is always something new to explore within this field which I love and I believe there is a need for it in every aspect of business. 

## Career Aspirations & Professional Growth   

Having had valuable experiences through previous work and internship opportunities, I’ve developed a strong interest in the field of risk. The ability to analyze patterns, anticipate potential risks, and create strategies to mitigate them aligns perfectly with my passion for data analytics.  

Data analytics plays a critical role in risk management, providing insights that help businesses make informed decisions and minimize uncertainties. I am eager to gain more experience in this field refining my technical skills in data analysis, and risk assessment while also strengthening my problem solving, critical thinking, and communication abilities. Every opportunity to work on real world challenges brings me closer to becoming a well rounded professional in this space.  

## Hobbies & Interests    

Beyond work, I am deeply passionate about broadening my global perspective. I thrive in environments where I can collaborate with people from diverse cultures, learning from their experiences and viewpoints.  

### **Creativity & Expression**  
I have a strong appreciation for art and creativity — sketching is something I enjoy as a way to unwind and express ideas visually. Whether it's through drawing or brainstorming innovative solutions, I love finding new ways to think outside the box. As well as this I also love interior design as a way to tell stories through spaces. Just like in sketching it's like starting from my blank canvas. 

### **Technology & AI Advancements**  
I’m fascinated by the rapid advancements in artificial intelligence and how they continuously reshape industries. Keeping up with the latest developments in AI not only excites me but also challenges me to think about the future of data analytics and risk management in a world where technology evolves at an unprecedented pace.  

### **Wellness & Productivity**  
I believe that taking care of my mental and physical well being is essential for excelling in my work. I make it a priority to focus on practices that keep my mind sharp and balanced whether that’s through mindfulness, exercise, or simply taking time for reflection. 